### ISSUE TITLE
[1.1.8] Fix crash Caused by: java.lang.NullPointerException: Attempt to read from field 'com.pixeltech.ptorrent.as com.pixeltech.ptorrent.aq.a' on a null object reference 4 points

### ISSUE THREAD

**Issue by dmxraj** [dmxraj/PT#27]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pixeltech.ptorrent.pro/com.pixeltech.ptorrent.AddTorrentFromIntentActivity}: java.lang.NullPointerException: Attempt to read from field 'com.pixeltech.ptorrent.as com.pixeltech.ptorrent.aq.a' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:5514)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.pixeltech.ptorrent.as com.pixeltech.ptorrent.aq.a' on a null object reference
    at com.pixeltech.ptorrent.a.ag.onCreateView(Unknown Source)
    at android.support.v4.app.Fragment.performCreateView(Unknown Source)
    at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
    at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
    at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source)
    at android.support.v4.app.FragmentActivity.onStart(Unknown Source)
    at com.pixeltech.ptorrent.AddTorrentFromIntentActivity.onStart(Unknown Source)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
    at android.app.Activity.performStart(Activity.java:6287)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2425)
    ... 9 more

1.1.7
Xperia Z5 Premium Dual (E6883)
it is stop while downloading 13.9 GB file

**Comment by dmxraj** [comment]
User tried this link
AIRLIFT (2016) HQ 1080p Blu-ray x264 Dolby-ATMOS 7.1 ESubs [DDR-ExclusivE] torrent
http://extratorrent.cc/torrent/4864433/AIRLIFT+%282016%29+HQ+1080p+Blu-ray+x264+Dolby-ATMOS+7.1+ESubs+%5BDDR-ExclusivE%5D.html

**Comment by dmxraj** [comment]
Logs are added to debug the issue.
Let's see what happens.
