### ISSUE TITLE
Fix crash java.lang.IllegalArgumentException 1 points

### ISSUE THREAD

**Issue by dmxraj** [dmxraj/PT#56]
Backtrace:
java.lang.IllegalArgumentException: Invalid % sequence %3­ at 123
    at java.net.URLDecoder.decode(URLDecoder.java:122)
    at java.net.URLDecoder.decode(URLDecoder.java:99)
    at com.pixeltech.ptorrent.PTorrentApplication.a(Unknown Source)
    at com.pixeltech.ptorrent.b.f.onClick(Unknown Source)
    at android.view.View.performClick(View.java:2485)
    at android.view.View$PerformClick.run(View.java:9080)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3714)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by dmxraj** [comment]
Rev 935
