### ISSUE TITLE
java.lang.RuntimeException: Unable to start service com.pixeltech.ptorrent.MyService 1 point

### ISSUE THREAD

**Issue by dmxraj** [dmxraj/PT#63]
java.lang.RuntimeException: Unable to start service com.pixeltech.ptorrent.MyService@3d4af993 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3320)
    at android.app.ActivityThread.access$2200(ActivityThread.java:177)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5938)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
    at com.pixeltech.ptorrent.MyService.onStartCommand(Unknown Source)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3303)
    ... 9 more

**Comment by dmxraj** [comment]
940
