### ISSUE TITLE
Fix crash due to java.lang.ArrayIndexOutOfBoundsException 4 points

### ISSUE THREAD

**Issue by dmxraj** [dmxraj/PT#68]
java.lang.ArrayIndexOutOfBoundsException
    at com.pixeltech.ptorrent.FileBrowserActivity.c(Unknown Source)
    at com.pixeltech.ptorrent.s.onItemClick(Unknown Source)
    at android.widget.AdapterView.performItemClick(AdapterView.java:284)
    at android.widget.ListView.performItemClick(ListView.java:3736)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:1975)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by dmxraj** [comment]
956
